# Generated by Django 3.2.1 on 2021-05-05 10:53

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models
import music_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(validators=[music_api.models.validate_positive])),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(validators=[music_api.models.validate_positive])),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('host', models.CharField(max_length=100)),
                ('participants', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=110, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(validators=[music_api.models.validate_positive])),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
