# Generated by Django 3.2.1 on 2021-05-07 04:15

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0002_auto_20210507_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=110, size=10),
        ),
    ]
